package de.MrBaumeister98.GunGame.Game.Listeners.Commands;

public enum ESubcommands {
	
	HELP,
	LIST,
	ADD,
	ADDSPAWN,
	ADDTANKSPAWN,
	ADDTURRETSPAWN,
	SETSPAWN,
	SETTANKSPAWN,
	SETTURRETSPAWN,
	TPSPAWN,
	TPTANKSPAWN,
	TPTURRETSPAWN,
	DELSPAWN,
	DELTANKSPAWN,
	DELTURRETSPAWN,
	LISTSPAWNS,
	LISTTANKSPAWNS,
	LISTTURRETSPAWNS,
	RESETSPAWNS,
	RESETTANKSPAWNS,
	RESETTURRETSPAWNS,
	SET,
	SAVE,
	LISTBUILDERS,
	ADDBUILDER,
	REMBUILDER,
	RESETBUILDERS,
	SETRESOURCEPACK,
	ENABLE,
	SETLOBBY,
	GIVE;

}
